import type { GlobalThemeOverrides } from 'naive-ui'
import { designColors } from './designColors'

/** Naive UI theme aligned with EasiFlux design tokens (PRD-07). */
export const naiveThemeOverrides: GlobalThemeOverrides = {
  common: {
    fontFamily: 'var(--font-sans)',
    fontFamilyMono: 'var(--font-mono)',
    fontSize: '13px',
    fontSizeMini: '11px',
    fontSizeTiny: '11px',
    fontSizeSmall: '12px',
    fontSizeMedium: '13px',
    fontSizeLarge: '14px',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    primaryColor: designColors.primary,
    primaryColorHover: designColors.primaryHover,
    primaryColorPressed: designColors.primaryPressed,
    primaryColorSuppl: designColors.primaryPressed,
    infoColor: designColors.primary,
    successColor: designColors.success,
    warningColor: designColors.warning,
    errorColor: designColors.danger,
    textColorBase: designColors.text,
    textColor1: designColors.text,
    textColor2: designColors.textSecondary,
    textColor3: designColors.textTertiary,
    bodyColor: designColors.surface,
    cardColor: designColors.card,
    modalColor: designColors.card,
    popoverColor: designColors.card,
    tableColor: designColors.surface,
    inputColor: designColors.surface,
    borderColor: designColors.border,
    dividerColor: designColors.border,
    hoverColor: designColors.accent,
    placeholderColor: designColors.textTertiary,
    iconColor: designColors.textSecondary,
    iconColorHover: designColors.text,
    iconColorPressed: designColors.text,
    actionColor: designColors.accent,
    clearColor: designColors.textTertiary,
    clearColorHover: designColors.textSecondary,
    clearColorPressed: designColors.text,
    scrollbarColor: designColors.border,
    scrollbarColorHover: designColors.textTertiary,
    progressRailColor: designColors.accent,
    closeIconColor: designColors.textSecondary,
    closeIconColorHover: designColors.text,
    closeIconColorPressed: designColors.text,
    boxShadow1: 'var(--ef-shadow-sm)',
    boxShadow2: 'var(--ef-shadow-md)',
    boxShadow3: 'var(--ef-shadow-lg)',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    fontWeightStrong: '600',
  },
  Input: {
    borderRadius: '8px',
    color: designColors.surface,
    colorFocus: designColors.surface,
    border: `1px solid ${designColors.border}`,
    borderHover: `1px solid ${designColors.primary}`,
    borderFocus: `1px solid ${designColors.primary}`,
    boxShadowFocus: `0 0 0 2px color-mix(in srgb, ${designColors.primary} 28%, transparent)`,
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '8px',
      },
    },
  },
  Checkbox: {
    borderRadius: '4px',
    colorChecked: designColors.primary,
    borderChecked: `1px solid ${designColors.primary}`,
  },
  Switch: {
    railColor: designColors.accent,
    railColorActive: designColors.primary,
  },
  Radio: {
    dotColorActive: designColors.primary,
    boxShadowActive: `0 0 0 2px color-mix(in srgb, ${designColors.primary} 28%, transparent)`,
  },
  Slider: {
    fillColor: designColors.primary,
    fillColorHover: designColors.primaryHover,
    handleSize: '14px',
  },
  DataTable: {
    borderRadius: '8px',
    thColor: designColors.accent,
    tdColor: designColors.surface,
    thTextColor: designColors.textSecondary,
    tdTextColor: designColors.text,
    borderColor: designColors.border,
  },
  Tooltip: {
    borderRadius: '6px',
    color: designColors.card,
    textColor: designColors.text,
  },
  Popover: {
    borderRadius: '8px',
  },
  Drawer: {
    borderRadius: '12px',
  },
  Dialog: {
    borderRadius: '12px',
  },
  Modal: {
    borderRadius: '12px',
    boxShadow: 'var(--ef-shadow-lg)',
  },
  Message: {
    borderRadius: '8px',
  },
  Notification: {
    borderRadius: '8px',
  },
}
